services:
  user-management-service:
    container_name: user-management-service
    image: user-management-service:release
    network_mode: host
    env_file:
      - ../.env
    build: ..
    volumes:
      - /home/mgreif/logs/user-management-service:/app/logs
